services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - frontend-net
      - backend-net

  web:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      target: development
    command: pnpm run dev
    env_file:
      - ./frontend/.env
    networks:
      - frontend-net
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/usr/src/app

  auth:
    build:
      context: .
      dockerfile: ./backend/apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./backend/apps/auth/.env
    volumes:
      - ./backend:/usr/src/app
    networks:
      - backend-net
    
  users:
    build:
      context: .
      dockerfile: ./backend/apps/users/Dockerfile
      target: development
    command: pnpm run start:dev users
    env_file:
      - ./backend/apps/users/.env
    volumes:
      - ./backend:/usr/src/app
    networks:
      - backend-net
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - backend-net
  
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
    networks:
      - backend-net


networks:
  frontend-net:
  backend-net:
