services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
      target: development
    command: pnpm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app